### ISSUE TITLE
CopyRight Issues

### ISSUE THREAD

**Issue by hex-plex** [Amshra267/Amshra267#1]
:sweat_smile: Bhai tujhe nahi lagraha tu mere README file se kuch jyada hi inspire nahi hogaya i dont know may be concidence but thought its a good conversation starter

**Comment by Amshra267** [comment]
Nahi yaar thoda tera dekha tha as a starter😂 but baaki sab kahi aur se chaapa tools ke icons badhiye the uske liye dhanyaawaad 📎🙏🙏😅😅

**Comment by Amshra267** [comment]
Waise inspired nhi fascinated ho sakta h🤔😁 Inspiration toh yahi se thi https://github.com/abhisheknaiidu 😅

**Comment by Terabyte17** [comment]
sabka inspiration wahi tha😁😁i guess😅

**Comment by Amshra267** [comment]
True😊

**Comment by hex-plex** [comment]
ye kya itna collaboration tho project ke liye kabhi nahi kiya , tum logo ek issue ke liye karrahe :laughing: , but yes i shame fully did copy my friends profile [Shubhanshu](https://github.com/shubhanshu02) :sweat_smile: hope he is not angry
